-- Baseline: captures the schema as it existed before Flyway was introduced
-- (previously managed by Hibernate's ddl-auto=update). Applied via
-- baseline-on-migrate rather than run directly against existing databases —
-- see application.properties. New databases run this for real.

CREATE TABLE app_users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    timestamp(6) with time zone,
    email         varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL
);

CREATE TABLE semesters (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active     boolean NOT NULL,
    end_date   date,
    name       varchar(255),
    start_date date,
    user_id    bigint REFERENCES app_users(id)
);

CREATE TABLE courses (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         varchar(255),
    credit_hours integer,
    name         varchar(255),
    professor    varchar(255),
    user_id      bigint REFERENCES app_users(id),
    semester_id  bigint REFERENCES semesters(id)
);

CREATE TABLE meetings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week varchar(255) CHECK (day_of_week IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY')),
    end_time    time(0),
    start_time  time(0),
    course_id   bigint REFERENCES courses(id),
    building    varchar(255),
    room_number varchar(255)
);

CREATE TABLE assignments (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    completed   boolean,
    description varchar(255),
    due_date    date,
    due_time    time(0),
    title       varchar(255),
    course_id   bigint REFERENCES courses(id)
);

CREATE TABLE events (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(255),
    event_date  date,
    title       varchar(255),
    meeting_id  bigint REFERENCES meetings(id),
    course_id   bigint REFERENCES courses(id)
);

CREATE TABLE finals (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date       date,
    end_time   time(0),
    location   varchar(255),
    start_time time(0),
    title      varchar(255),
    course_id  bigint REFERENCES courses(id)
);

CREATE TABLE grade_categories (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              varchar(255),
    placeholder_score double precision,
    weight_percent    double precision,
    course_id         bigint REFERENCES courses(id)
);

CREATE TABLE grade_scale_entries (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    letter      varchar(255),
    min_percent double precision,
    course_id   bigint REFERENCES courses(id)
);

CREATE TABLE graded_items (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    percent_score   double precision,
    points_earned   double precision,
    points_possible double precision,
    title           varchar(255),
    category_id     bigint REFERENCES grade_categories(id)
);

CREATE TABLE syllabuses (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_data   oid,
    file_name   varchar(255),
    uploaded_at timestamp(6),
    course_id   bigint REFERENCES courses(id)
);

CREATE TABLE user_settings (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    home_address   varchar(255),
    home_latitude  double precision,
    home_longitude double precision,
    user_id        bigint REFERENCES app_users(id)
);
