-- Plan Ahead: a per-user wishlist of courses to consider for a future
-- semester (planned_courses), backed by a shared, global cache of course/
-- instructor/syllabus data scraped from the public UGA bulletin
-- (external_courses / external_course_instructors / external_syllabi).
-- The cache is shared across all users since it's public data, not personal.

CREATE TABLE planned_courses (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint REFERENCES app_users(id),
    subject_code  varchar(255),
    course_number varchar(255),
    term_label    varchar(255),
    created_at    timestamp(6)
);

CREATE TABLE external_courses (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulletin_course_id bigint UNIQUE,
    subject_code       varchar(255),
    course_number      varchar(255),
    title              varchar(255),
    last_scraped_at    timestamp(6)
);

CREATE TABLE external_course_instructors (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_course_id  bigint REFERENCES external_courses(id),
    instructor_name     varchar(255),
    syllabus_file_id    bigint,
    last_scraped_at     timestamp(6)
);

CREATE TABLE external_syllabi (
    id                             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_course_instructor_id  bigint UNIQUE REFERENCES external_course_instructors(id),
    file_name                      varchar(255),
    scraped_at                     timestamp(6),
    file_data                      oid
);
