CREATE TABLE password_reset_tokens (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint REFERENCES app_users(id),
    token      varchar(255) NOT NULL UNIQUE,
    expires_at timestamp(6),
    used       boolean NOT NULL DEFAULT false
);
